### ISSUE TITLE
[Documentation] Missing documentation for 00023_PIX2PIXHD_BREAST_DCEMRI

### ISSUE THREAD

**Issue by LHamnett** [RichardObi/medigan#67]
Hi, 

It seems that there has been a GAN added which has been trained on the Duke-Breast-Cancer-MRI. However in the documentation page, this GAN does not have information about the parameters this model accepts. 

I am also working on a research paper that involves training a GAN on the DCEMRI dataset, can you confirm if this GAN was trained on all of the images regardless of metadata or if it is possible to return a trained GAN for a specific class eg cancer type. 

Thanks.
Leon

**Comment by LHamnett** [comment]
@RichardObi for visibility

**Comment by RichardObi** [comment]
Hi @LHamnett, 
thank you very much for pointing out this issue. Model 23 was missing in the docs due to the .readthedocs.yaml requiring an [update to version 2](https://blog.readthedocs.com/migrate-configuration-v2/). The documentation for model 23 will now become available [here](https://medigan.readthedocs.io/en/latest/models.html#pix2pixhd-breast-dcemri). 
Apart from that, you may also find more detailed info for training this model in this [repo](https://github.com/RichardObi/pre_post_synthesis) and in this [paper](https://arxiv.org/abs/2311.10879). The GAN was trained on 668 cases (mixed cancer types) out of the 922 cases available in the Duke-Breast-Cancer-MRI. You can find the 254 cases excluded from GAN training [here](https://github.com/RichardObi/pre_post_synthesis/blob/main/synthesis/utils/get_training_patient_ids.py#L21-L71). 

Hope this helps and feel free to reach out anytime.
